stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: ./src
      tag: owo-converter:v1.0.${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: docker.atriarch.systems
    env:
      PLUGIN_MTU: "1400"
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./service.yaml
timeout: 10
notification: {}
