stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: ./src
      tag: owo-converter:v1.0.${CICD_EXECUTION_SEQUENCE}
      registry: docker-registry.fun.svc.cluster.local:34443
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./service.yaml
timeout: 10
notification: {}
