stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: ./src
      tag: owo-converter:v1.0.${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: https://nexus.atriarch.systems/repository/atriarch-docker
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./service.yaml
timeout: 10
notification: {}
