apiVersion: serving.knative.dev/v1 # Current version of Knative
kind: Service
metadata:
  name: owo-converter # The name of the app
  namespace: owo-converter # The namespace the app will use
  labels:
    domain: drinkpoint
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "10"
    spec:
      containers:
        - name: owo-converter
          image: ${CICD_IMAGE}:v1.0.${CICD_EXECUTION_SEQUENCE} # The URL to the image of the app
          livenessProbe:
            httpGet:
              path: /
      imagePullSecrets:
      - name: atriarch-systems-docker-group
