name: PR Validation

on:
  pull_request:
    branches: [ master ]

env:
  # Repository-specific variables
  IMAGE_NAME: uwuconverter
  DOCKERFILE_PATH: ./src/Dockerfile

jobs:
  test:
    runs-on: [self-hosted, linux]  # Adjust labels for your self-hosted runners
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Buildx for testing
      uses: docker/setup-buildx-action@v3
      with:
        driver: kubernetes
        driver-opts: |
          namespace=actions-runner-system
          serviceaccount=buildx
          nodeselector=kubernetes.io/arch=arm64
          qemu.install=true
        install: true
    
    - name: Log in to Docker Registry (for private base images/packages)
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and run tests in container
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ${{ env.DOCKERFILE_PATH }}
        target: build  # Stop at the build stage to run tests
        platforms: linux/amd64
        push: false
        build-args: |
          NUGET_USER=${{ secrets.NUGET_USERNAME }}
          NUGET_PASS=${{ secrets.NUGET_PASSWORD }}
        outputs: type=cacheonly
    
    - name: Run tests in built container
      run: |
        # Create a test container from the build stage
        docker buildx build \
          --target build \
          --platform linux/amd64 \
          --build-arg NUGET_USER=${{ secrets.NUGET_USERNAME }} \
          --build-arg NUGET_PASS=${{ secrets.NUGET_PASSWORD }} \
          --load \
          --tag test-image \
          -f ${{ env.DOCKERFILE_PATH }} .
        
        # Run tests in the container
        docker run --rm \
          --workdir /src \
          test-image \
          dotnet test ../UwUConverter.Test/UwUConverter.Tests.csproj --logger "console;verbosity=detailed"

  build-validation:
    needs: test
    runs-on: [self-hosted, linux]  # Adjust labels for your self-hosted runners
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Buildx (k8s driver + qemu)
      uses: docker/setup-buildx-action@v3
      with:
        driver: kubernetes
        driver-opts: |
          namespace=actions-runner-system
          serviceaccount=buildx
          nodeselector=kubernetes.io/arch=arm64
          qemu.install=true
        install: true
    
    - name: Log in to Docker Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Extract metadata for validation
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ secrets.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=pr
    
    - name: Build Docker image (validation only)
      id: build
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ${{ env.DOCKERFILE_PATH }}
        platforms: linux/amd64
        push: false  # Don't push for PRs
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          NUGET_USER=${{ secrets.NUGET_USERNAME }}
          NUGET_PASS=${{ secrets.NUGET_PASSWORD }}
        outputs: type=cacheonly
    
    - name: PR Build Summary
      run: |
        echo "✅ Tests passed successfully"
        echo "✅ Docker image builds successfully"
        echo "📦 Image would be tagged as: ${{ steps.meta.outputs.tags }}"
        echo "🚀 Ready for merge to master"
